on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-image:
    uses: beeldengeluid/gha-workflows/.github/workflows/build-push-image.yml@arm-build
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
