name: CICD

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-push-image:
    uses: gb-beng/gha-workflows/.github/workflows/build-push-image.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
  integration-tests:
    needs: [build-push-image]
    uses: gb-beng/gha-workflows/.github/workflows/trigger-integration-tests.yml@main
    with:
      image: ${{ needs.build-push-image.outputs.oci }}
      workload: beng-lod-server # could be repo/...
  deploy:
    needs: [integration-tests]
    uses: gb-beng/gha-workflows/.github/workflows/trigger-deploy.yml@main
